### ISSUE TITLE
Automate tasks

### ISSUE THREAD

**Issue by 3runoDesign** [themosis/theme#5]
It would be nice to automate the tasks to build the JS, CSS and the like using or Gulp or Grunt ... And not forgetting Bower.

I would like to do this. But I'm a little confused where I can implement this, I think it's here. :sweat_smile:

**Comment by jlambe** [comment]
Yes it's in the theme. I haven't done it because people have their preferences. I mainly use Grunt but others prefer Gulp or direct use of npm.
You can set your `package.json` at the root of the theme, It will be safe their. Note that there is new folder structure coming for the next version. (check the master branch)

**Comment by jlambe** [comment]
Finally I won't put a pre-processor script inside the theme for the moment. Even for me, the method has changed to use webpack over gruntjs. The best thing for your work would be to fork the theme and add your own scripts. Then update your composer.json file to catch your fork in place of the default `themosis-theme`.
